### ISSUE TITLE
Complexity measurement

### ISSUE THREAD

**Issue by larshum** [slarse/lektor#2]
* Count the cyclomatic complexity of 5 out of 10 selected functions with very high CC by hand.
* Answer following questions in report:
    1. What are your results? Did everyone get the same result? Is there something that is unclear? If you have a tool, is its result the same as yours?
    2. Are the functions/methods with high CC also very long?
    3. What is the purpose of these functions? Is it related to the high CC?
    4. If your programming language uses exceptions: Are they taken into account in the CC count? If you think of an exception as another possible branch (to the catch block or the end of the function), how is the CC affected?
    5. Is the documentation of the function clear about the different possible outcomes induced by different branches taken?

**Comment by rouwaydhanna** [comment]
ten functions of high cc:

* get_structure_hash in lektor/utils.py cc=14
* tokenize in lektor/metaformat.py cc=15
* locate_executable in lektor/utils.py cc=20
* merge in lektor/utils.py cc=10
* decode_flat_data in lektor/utils.py cc>10
* content_file_info_cmd in lektor/cli.py cc=11
* find_files in lektor/sourcesearch.py cc=5
* ~plugins_list_cmd in lektor/cli.py cc=9~ `get_image_info` in lektor/imagetools.py, cc=14
* discover_relevant_flowblock_models in lektor/types/flow  cc=10
* prune_file_and_folder in lektor/utils.py cc=9

**Comment by larshum** [comment]
We will count the cyclomatic complexity of the following functions:
* merge in [lektor/utils.py](https://github.com/slarse/lektor/blob/master/lektor/utils.py#L229)
* find_files in [lektor/sourcesearch.py](https://github.com/slarse/lektor/blob/master/lektor/sourcesearch.py#L102) (we realised this one probably has too low CC, but we left it since it is still pretty long and complicated)
* plugins_list_cmd in [lektor/cli.py](https://github.com/slarse/lektor/blob/master/lektor/cli.py#L545)
* content_file_info_cmd in [lektor/cli.py](https://github.com/slarse/lektor/blob/master/lektor/cli.py#L432)
* discover_relevant_flowblock_models in [lektor/types/flow.py](https://github.com/slarse/lektor/blob/master/lektor/types/flow.py#L17)
* get_image_info in [lektor/imagetools.py](https://github.com/slarse/lektor/blob/master/lektor/imagetools.py#L323)
