### ISSUE TITLE
Document "onboarding" answers

### ISSUE THREAD

**Issue by larshum** [slarse/lektor#23]
How good is the "onboarding" documentation?

1. How easily can you build the project? Briefly describe if everything worked as documented or not:
    1. Did you have to install a lot of additional tools to build the software? Were those tools well documented?
    2. Were other components installed automatically by the build script?
    3. Did the build conclude automatically without errors?
    4. How well do examples and tests run on your system(s)?
2. Do you plan to continue or choose another project?

**Comment by slarse** [comment]
As a note on this one, `imagemagick` needed to be installed separately. It's somewhere in the docs.

**Comment by larshum** [comment]
Yeah, I decided to not specify that, I just wrote `The README contains a link to an installation guide which states what Lektor depends on and how you install it.`

Also, I'm closing this now because I forgot to do it when I merged :smile:
