### ISSUE TITLE
Purpose of chosen functions

### ISSUE THREAD

**Issue by rouwaydhanna** [slarse/lektor#56]
Comment here the purpose purpose of the functions you were assigned, and we'll include it in the report.

**Comment by mudaliarkartik** [comment]
- utils.merge
Merge two lists/dictionary values together.

- metaformat.tokenize
    tokenizes an iterable of newlines as bytes into key value
    pairs out of the lektor bulk format.  By default it will process all
    fields, but optionally it can skip values of uninteresting keys and
    will instead yield `None`. 
    This will not perform any other processing on the data other than 
    decoding and basic tokenizing.

**Comment by larshum** [comment]
* `lektor.utils.decode_flat_data`:
decodes data from an iterator given from parsing a .ini file into a dictionary of the given dictionary type, or a regular dictionary if no argument is given.
* `lektor.utils.prune_file_and_folder`:
takes a “name” filepath and a “base” filepath, where the latter is supposed to be a parent directory of the former. The method then repeatedly tries deleting the file or folder at the “name” filepath while walking higher up in the hierarchy until it fails, either because it reaches the “base” filepath or a non-empty subdirectory of the “base” filepath.

**Comment by slarse** [comment]
* `lektor.cli.content_file_info_cmd`
    - CLI command for printing out information about Lektor project files.
* `lektor.imagetools.get_image_info`
    - Utility command for parsing header info in `png`, `jpg`, `svg` and `gif` images. More specifically, given a file descriptor, it returns filetype, height and width if the image is supported. For unsupported file formats, it just returns `(None, None, None`).

**Comment by rouwaydhanna** [comment]
* `lektor.utils.get_structure_hash`:
Given a Python structure, this generates a md5 hash. The method maps python structures to bytes which the md5 gets updated with and later digested. Not all Python types are supported, but quite a few are. 
* `lektor.utils.locate_executable`:
Searches and returns the first found path to an executable file. Takes the name of the executable file to search for and current working directory.

**Comment by mnil2** [comment]
* `lektor.sourcesearch.find_files`:
Queries a file database for all the files that satisfy some given filters (language, types, etc.). Apart from the filters, the query itself is a simple substring match of either the filename or the absolute filepath.

* `lektor.types.flow.discover_relevant_flowblock_models`:
First some terminology. A flow is just a bunch of flowblocks. It's not important to know exactly what a flowblock is, but they are basically a set of properties with a unifying name. The function will try to find and return every flowblock given a list of flowblock names and a database. Or, if no names are provided, it will instead return all the flowblocks from the database.
